### PR TITLE
Add TVM VirtualMachine Runtime

### PR DESCRIPTION
**Pull request by Ailurus1**
Hello, @apeskov
In multiprocessing pool in `backend_tvm.py` the default start method `fork` is used, but sometimes it can cause some problems in case of segmentation faults which usually cannot process correctly and may look like a deadlock (actually there is an infinite creation of chile processes) so its hard to be identified. I tried to use `spawn` start method so at least it is possible to correctly stop program and get proper warning message. In theory `spawn` method may work slower than `fork`, so could you please provide some feedback about whether this method be used here. In my local tests both methods give almost the same performance.
Also can you please describe expected behaviour of `arena_num` and `arena_size`  variables
Currently `arena_num` seems to have as values only a number of cpu cores ([set](https://github.com/Deelvin/inference/blob/fd6486a0483de3175c67bdd84576eb5f4f406be7/vision/classification_and_detection/python/main.py#L465) in `main.py`) or 1 ([set](https://github.com/Deelvin/inference/blob/fd6486a0483de3175c67bdd84576eb5f4f406be7/vision/classification_and_detection/python/backend_tvm.py#L313) as 1 at worker initializer) and `arena_size` is maually [set](https://github.com/Deelvin/inference/blob/fd6486a0483de3175c67bdd84576eb5f4f406be7/vision/classification_and_detection/python/main.py#L466) as 4 in `main.py` and never change.

### CODE REVIEW

**Comment by Ailurus1** [comment]
@apeskov
I did a bit more descriptive analysis here. Actually `fork` is still the fastest but not always and it is still not that safe as `spawn`
photo_2023-05-17_22-29-44

**Comment by apeskov** [comment]
Hi @Ailurus1, I have have no objections about using "swap" by default. But I guess you should provide clear explanation what is a problem with "fork", what is a real reason of segfault/deadlock/infinit_loop, and how "swap" may solve it. My naive notion about fork/swap difference doesn't explain my how it may help us. 

Also I was very surprised that swap and fork demonstrate a difference performance in terms of "Samples per Second". I expect identical results. Are you sure that accuracy of your measurements allow you to detect a difference 3.6 vs 3.8?

**Comment by apeskov** [comment]
@Ailurus1 
> expected behaviour of `arena_num` and `arena_size` variables

Arena is a term from OMP thread engine. Arena incapsulate a branch of threads which works simultaneously on the same task. Threads from different arenas processes different tasks. You may treat "arena" as equivalent of term "worker". One worker has a limited num of threads (`arena_size`) and process one "infer_reqest", each convolution operator inside network will be executed in parallel with using all threads from this arena. Ideally `arena_num * arena_size == os.cpu_count()`.

**Example:**
Your system has 128 cores. To utilise all cores you should create 128 threads. Also you may split it on 8 workers with 16 threads per worker. Each sample will be submitted asynchronous to one of idle worker. Each convolution operator will be paralleled only on 16 individual threads. Imagine that you have to process 1000 samples. Each workers will process ~125 samples with using 16 threads. Each worker works independently and does't affect others because it has its own set of threads. And totally this configuration utilise CPU with 100%. This thread configuration is called  `arena_num = 8, arena_size = 16`.

> Currently arena_num seems to have as values only a number of cpu cores.

That's not true. This value specified outside of main script by user. You may specify this value as you want. This value means how mach workers should be used. Unfortunately this main.py script was originally designed for other purposes, just functional demo, so the naming of script arguments is incorrect, it should be "num_workers".
 
> `arena_size` is maually set as 4

Yep, it's hardcoded. It should be also configurable outside of script.

Conclusion, thread configuration `arena_num = ??, arena_size = ??` is platform and model specific and should be configurable.

**Comment by Ailurus1** [comment]
Thank you for the answers
> But I guess you should provide clear explanation what is a problem with "fork", what is a real reason of segfault/deadlock/infinit_loop, and how "swap" may solve it

During the launch of automation for MLPerf inference an unexpected deadlock often occured and there were no warning messages or exceptions and in attempt to stop the program there was infinite process generation and the program could not be terminated when running in WSL or in Docker container (only with `wsl --shutdown` or manually stopping container). The problem was in batch size, which is not able to dynamically change yet and it always run with the same value 32 that may be too big for some CPUs (as currently in a single CPU it loads all cores with processes and each process has this batch size 32) and cause segmentation faults. And it took a lot of time to figure out the source of the problem as with `fork` start method program just stops with no log messages and cannot be terminated, but with `spawn` it stops with message about segfault and can be terminated simply with `Ctrl+C`. So, the main motivation of switching start method from `fork` to `spawn` is to correctly identify segmentation faults and be able to easily terminate program. 

Probably, start method can be configurable and `spawn` should be used in debugging purposes and `fork` in performance analysis as it can be faster according to [documentation](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods).

> Also I was very surprised that swap and fork demonstrate a difference performance in terms of "Samples per Second". I expect identical results. Are you sure that accuracy of your measurements allow you to detect a difference 3.6 vs 3.8?

I took the results from CMind logs of MLPerf inference automation as mean of 20 runs. As There was precision about 4-5 digits after point.

> Conclusion, thread configuration arena_num = ??, arena_size = ?? is platform and model specific and should be configurable.

Ok, will work on it

**Pull request closed without merging**
